export const PAUSE = 'PAUSE';

export const SET_BLOCK_NUMBER = 'SET_BLOCK_NUMBER'
export const SET_BLOCK_NUMBER_SAGA = 'SET_BLOCK_NUMBER_SAGA';

export const INITIALIZE_WEB3 = 'INITIALIZE_WEB3';

export const INITIALIZE_STATE_SAGA = 'INITIALIZE_STATE_SAGA';

export const SET_BLOCK_ARRAY = 'SET_BLOCK_ARRAY';
